apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eosio-testnet.biosfullname" . }}
  labels:
    app: {{ include "eosio-testnet.name" . }}
    chart: {{ include "eosio-testnet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: bios
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            - /usr/local/bin/boot-bios.sh
            - --p2p-server-address 
            - {{ include "eosio-testnet.biosfullname" . }}:9876
          args: {{ toJson .Values.args }}
          ports:
            - containerPort: 8888
              protocol: TCP
            - containerPort: 9876
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /v1/chain/get_info
              port: 8888
          volumeMounts:
            - name: config-volume
              mountPath: "/usr/local/etc/eosio/genesis.json"
              subPath: genesis.json
      restartPolicy: OnFailure
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "eosio-testnet.fullname" . }}

