apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "eosio-testnet.nodeosfullname" . }}
  labels:
    app: {{ include "eosio-testnet.name" . }}
    chart: {{ include "eosio-testnet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodeos
      release: {{ .Release.Name }}
  serviceName: {{ include "eosio-testnet.headlessService" . }}
  template:
    metadata:
      labels:
        app: nodeos
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bash
            - /eosio/boot-nodeos.sh
          args: {{ toJson .Values.args }}
          env:
            - name: BIOS_ADDR
              value: {{ include "eosio-testnet.biosfullname" . }}:8888
            - name: NDOES
              value: "{{ .Values.replicaCount }}"
            - name: PRODUCERS
              value: "{{ .Values.producerCount }}"
            - name: GENESIS_KEY
              value: "{{ .Values.genesis.signatureProvider }}"
            - name: SERVICE_PATTERN
              value: {{ include "eosio-testnet.nodeosfullname" . }}-{}.{{ include "eosio-testnet.headlessService" . }}
            - name: PRODUCER_KEYS
              value: "{{ .Values.producerKeys }}"
          ports:
            - containerPort: 8888
              protocol: TCP
            - containerPort: 9876
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /v1/chain/get_info
              port: 8888
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /eosio
{{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /root/.local/share/eosio
{{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "eosio-testnet.fullname" . }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: {{ include "eosio-testnet.name" . }}
          chart: {{ include "eosio-testnet.chart" . }}
          release: {{ .Release.Name }}
          heritage: {{ .Release.Service }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}        
      {{- end }}
{{- end }}